<script setup>

import GuestLayout from '@/Layouts/GuestLayout.vue';

const props = defineProps({
    home: String,
    posts: Object,
    taxonomies: Object
});

</script>

<template>



<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">

    <url>
		<loc>https://duhocvic.com/</loc>
		<lastmod>2023-12-13T04:10:03+00:00</lastmod>
	</url>
    <template v-for="by_type in posts">
        <template v-for="post in by_type">
        	<url >
                <loc>{{ post.name }}</loc>
                <lastmod>{{ post.created_at }}</lastmod>
            </url>
        </template>
    </template>


</urlset>
<!-- XML Sitemap generated by Yoast SEO -->

<!--         <div class="py-8 px-4">
            <div v-for="by_type in posts">
                <h2>tye:</h2>
                <ul>
                    <li v-for="post in by_type">{{ post.title }}</li>
                </ul>
            </div>

        </div> -->
</template>
